services:
  deepseek-ocr:
    build:
      context: ./docker
      dockerfile: Dockerfile.transformers
    container_name: nunoocr_deepseek
    restart: unless-stopped

    # Traefik labels for timeout configuration
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.nunoocr.loadbalancer.server.timeout=300s"
      - "traefik.http.routers.nunoocr.timeout.idle=300s"
      - "traefik.http.routers.nunoocr.timeout.read=300s"
      - "traefik.http.routers.nunoocr.timeout.write=300s"

    # Uncomment for NVIDIA GPU support
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
    # runtime: nvidia

    environment:
      # Model configuration
      - MODEL_NAME=deepseek-ai/DeepSeek-OCR
      - HOST=0.0.0.0
      - PORT=8000
      - API_KEY=${API_KEY:-}

      # Version tracking
      - GIT_COMMIT=${GIT_COMMIT:-unknown}

      # PyTorch CPU optimizations
      - OMP_NUM_THREADS=4
      - MKL_NUM_THREADS=4
      - TORCH_NUM_THREADS=4

      # Hugging Face settings
      - HF_HOME=/root/.cache/huggingface
      - TRANSFORMERS_CACHE=/root/.cache/huggingface

      # Disable Flash Attention (force CPU-compatible attention)
      - DISABLE_FLASH_ATTENTION=1
      - USE_FLASH_ATTENTION=0
      - PYTORCH_ENABLE_MPS_FALLBACK=1

    ports:
      - "8765:8000"

    volumes:
      # Cache Hugging Face models (persistent)
      - huggingface-cache:/root/.cache/huggingface
      # Optional: logs
      - ./logs:/app/logs

    # Healthcheck disabled temporarily to allow initial model loading (10-15 min)
    # Re-enable after first successful deployment
    # healthcheck:
    #   test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 5
    #   start_period: 180s  # Give extra time for model download + loading

    # Resource limits (CPU-optimized)
    # Adjust based on your server capacity
    deploy:
      resources:
        limits:
          memory: 14G  # Max 14GB RAM (CX43 has 16GB total)
        reservations:
          memory: 10G  # Reserve 10GB RAM

    shm_size: '2gb'

    networks:
      - ocr-network

networks:
  ocr-network:
    driver: bridge
    name: nunoocr_network

volumes:
  huggingface-cache:
    name: nunoocr_hf_cache
